include:

exclude: 
  - TODO
  - README.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - "_providers/example.com.md"
  - target

defaults:
-
  scope:
    path: "_providers"
  values:
    layout: "provider"
      

collections:
  providers:
    output: true
    permalink: /:slug
