# include:

exclude: 
  - TODO
  - README.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - "_providers/example.com.md"
  - target
  - build.rs
  - Cargo.*
  - rust-toolchain
  - .travis.yml
  - vendor
  - .bundle
  - "_providers/old"

defaults:
-
  scope:
    path: "_providers"
  values:
    layout: "provider"
      

collections:
  providers:
    output: true
    permalink: /:slug
